name: Wake Up Render Backends

on:
  schedule:
    - cron: '*/10 * * * 1-5'
  workflow_dispatch:

jobs:
  ping-backends:
    runs-on: ubuntu-latest

    steps:
      - name: Wake up APIs
        run: |
          echo "Starting server wake-up routine..."

          curl -s -o /dev/null -w "Notepad Backend Status: %{http_code}\n" https://secure-notepad-ne8r.onrender.com/health
          curl -s -o /dev/null -w "Chat Backend Status: %{http_code}\n" https://realtime-chat-app-r204.onrender.com/health
          curl -s -o /dev/null -w "RAG Backend Status: %{http_code}\n" https://rag-project-zh1z.onrender.com/health

          echo "All ping requests sent successfully."
